### ISSUE TITLE
(V2) Contributor Console - Corporate Select Company Issues

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla-contributor-console#15]
## Background
Issue2 - Placeholder color is different
1. Launch Launch http://localhost:4200/corporate-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f46726
2. Color of placeholder 'Type your Company Name' is different from wireframe spec
![image](https://user-images.githubusercontent.com/60865903/82552077-109b8180-9b7f-11ea-9bf9-83c4f26f98dc.png)

![image](https://user-images.githubusercontent.com/60865903/82551983-e649c400-9b7e-11ea-8db0-b5ec0e400efe.png)

**_Issue2 - Drop down does not disappear and selected company is not displayed in bold_**
1. Launch http://localhost:4200/corporate-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f46726
2. Select a company
3. Observed that drop down does not disappear and selected company is not displayed in bold
![image](https://user-images.githubusercontent.com/60865903/82550938-f365b380-9b7c-11ea-8c33-b9e7f3ae6f55.png)

**_Issue3 - Entire text in placeholder is not proper case_**
Observed **your** starts with small letter and other words are in proper case in placeholder 'Type your Company Name'

**_Issue4 - Proceed button is enabled even before selecting the company_**
1. 1. Launch http://localhost:4200/corporate-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f46726
2. Search for company
3. Observed that Proceed button is enabled even before company selected
![image](https://user-images.githubusercontent.com/60865903/82633030-a84cae80-9c17-11ea-8e79-e37650d891cb.png)

**Comment by amolsontakke3576** [comment]
@nirupamav : 
For **Issue 2** :` Selected company is not displayed in bold` not possible because we can set only one font weight to input box and is above case when user type company name font weight is normal and after selection it is bold which in contradict. 
For **Issue 3** : `Entire text in placeholder is not proper case` it is as per the wireframe (PFA) still, It is designing issue, so I will correct it.
![Screenshot from 2020-05-22 12-11-10](https://user-images.githubusercontent.com/56335654/82639753-fb7a2d80-9c26-11ea-9c43-bde636c63ef3.png)

**Comment by nirupamav** [comment]
Verified that except for issue1 and issue2 all other issues are fixed. Will check with Pranab about these 2 issues and if required will log a ticket in EasyCLA board. Closing the ticket
