### ISSUE TITLE
(V2) Contributor Console Homepage - "What type of contributor are you?" display is not as per UI specifications mentioned in wireframe

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla-contributor-console#6]
## Background
**Note: Deployed and tested locally**
1. Launch the Contributor Console for the project and user
2. Observed that "What type of contributor are you?" display is not as per UI specifications mentioned in wireframe
3. **Issue1 - Width and height is not as per wireframe**
![image](https://user-images.githubusercontent.com/60865903/81378184-7a9a3c80-9124-11ea-815f-b1b1e81b19a6.png)
4. **Issue2 - Line Height is 39px in UI but as per wireframe it should be 1px**
5. **Issue3 - Padding is 15px in UI but as per wireframe it should be 5px**

**Comment by amolsontakke3576** [comment]
@nirupamav Please check only `look and feel` rather than original measurement in wireframe. We are using bootstrap and making it compatible to mobile and tablet view  so html pattern used in wireframe  can not use it directly. :)

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav Got a chance to go through some basic in html and below is the explanation on issues
1. Line height and Div height is different and by default it is normal or 20% of font size. So in our case it is normal and not a 39px.
2. Padding may be vary because of HTML design style. HTML pattern followed by wireframe not always same it actual framework.

But still I have figured out which wireframe properties you can follow and which can be avoided.

Basic wireframes Properties we can follow.
1. font-family/font-size/font-style/font-weight/color
2. background-color/background-image
3. text/text-align/line-height
4. border/border-color/border-radius.

Below are the properties which can applicable on condition
1. width.
2. height.
3. padding
4. margin

Below are the properties which need to avoid
1. X
2. Y

Thanks.
